(setf x (array (loop for i in (iseq -9 10) collect (/ i 3))
                :dimensions '(20)))
(setf y (array (loop for i in (iseq -9 10) collect (/ i 3))
                :dimensions '(20)))
(setf z #'(lambda (x y)
            (+ (* .6 (exp (* -2 (+ (* x x) (* y y)))))
               (* .4 (exp (* -2 (+ (* (- x 1.5)
                                      (- x 1.5))
                                   (* (- y 1.5)
                                      (- y 1.5)))))))))
(setf x (array (loop for i in (iseq -2 2) collect i)
                :dimensions '(5)))
(setf y (array (loop for i in (iseq -2 2) collect i)
                :dimensions '(5)))
(setf z #'(lambda (x y)
            (exp (* -2 (+ (* x x) (* y y))))))

(surface-plot :x x :y y :surface-function z)
