(in-package :wb)

(defmethod initialize-instance :after ((self button) &rest initargs))
(defmethod initialize-instance :after ((self y-or-n-dialog) &rest initargs))
(defmethod initialize-instance :after ((self list-dialog-item) &rest initargs))
(defmethod initialize-instance :after ((self list-dialog) &rest initargs))
(defmethod initialize-instance :after ((self text-dialog) &rest initargs))
(defmethod wb-refresh ((self list-dialog)) (call-next-method))
(load "Source/Window-Basics/Mouse/mouse-clx2")
(load "Source/Window-Basics/Prompt/dialog-items-clx")
(load "Source/Window-Basics/Prompt/dialog-clx")
(load "Source/Window-Basics/Prompt/check-items-clx")
(load "Source/Window-Basics/Prompt/collect-input-clx")
(load "Source/Window-Basics/Prompt/pick-one-clx")
(load "Source/Window-Basics/Prompt/prompt-clx2")
